---
- import_tasks: system.yml
  tags: [server, server-system]

- import_tasks: python.yml
  tags: [server, server-python]

- import_tasks: ntp.yml
  tags: [server, server-ntp]

- import_tasks: timezone.yml
  tags: [server, server-timezone]