---
- name: restart ntp
  service:
      name: ntp
      enabled: yes
      state: restarted

- name: stop ntp
  service:
      name: ntp
      enabled: yes
      state: stopped

- name: start ntp
  service:
      name: ntp
      enabled: yes
      state: started